use std::fs;
use std::path::{Path, PathBuf};

use schemars::schema_for;
use serde_json::Value;
use sha2::{Digest, Sha256};
use theway_contract::extension::{
    ExtensionActionBatch, ExtensionCatalogEntry, ExtensionClientContribution,
    ExtensionCommandDescriptor, ExtensionCommandOutcome, ExtensionDiagnostic,
    ExtensionDurableEntry, ExtensionEventEnvelope, ExtensionHookContract, ExtensionPackageManifest,
    ExtensionTrustRecord,
};

pub const ARTIFACT_PATHS: &[&str] = &[
    "schemas/action-batch.schema.json",
    "schemas/catalog-entry.schema.json",
    "schemas/client-contribution.schema.json",
    "schemas/command-descriptor.schema.json",
    "schemas/command-outcome.schema.json",
    "schemas/diagnostic.schema.json",
    "schemas/durable-entry.schema.json",
    "schemas/event-envelope.schema.json",
    "schemas/hook-contract.schema.json",
    "schemas/package-manifest.schema.json",
    "schemas/trust-record.schema.json",
    "theway-extension.d.ts",
];

pub fn generate(output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let schemas = schema_documents()?;
    fs::create_dir_all(output_dir.join("schemas"))?;
    for (relative_path, schema) in &schemas {
        let mut encoded = serde_json::to_string_pretty(schema)?;
        encoded.push('\n');
        fs::write(output_dir.join(relative_path), encoded)?;
    }
    fs::write(
        output_dir.join("theway-extension.d.ts"),
        typescript(&schemas)?,
    )?;
    Ok(())
}

fn schema_documents() -> Result<Vec<(&'static str, Value)>, serde_json::Error> {
    Ok(vec![
        (
            "schemas/action-batch.schema.json",
            serde_json::to_value(schema_for!(ExtensionActionBatch))?,
        ),
        (
            "schemas/catalog-entry.schema.json",
            serde_json::to_value(schema_for!(ExtensionCatalogEntry))?,
        ),
        (
            "schemas/client-contribution.schema.json",
            serde_json::to_value(schema_for!(ExtensionClientContribution))?,
        ),
        (
            "schemas/command-descriptor.schema.json",
            serde_json::to_value(schema_for!(ExtensionCommandDescriptor))?,
        ),
        (
            "schemas/command-outcome.schema.json",
            serde_json::to_value(schema_for!(ExtensionCommandOutcome))?,
        ),
        (
            "schemas/diagnostic.schema.json",
            serde_json::to_value(schema_for!(ExtensionDiagnostic))?,
        ),
        (
            "schemas/durable-entry.schema.json",
            serde_json::to_value(schema_for!(ExtensionDurableEntry))?,
        ),
        (
            "schemas/event-envelope.schema.json",
            serde_json::to_value(schema_for!(ExtensionEventEnvelope))?,
        ),
        (
            "schemas/hook-contract.schema.json",
            serde_json::to_value(schema_for!(ExtensionHookContract))?,
        ),
        (
            "schemas/package-manifest.schema.json",
            serde_json::to_value(schema_for!(ExtensionPackageManifest))?,
        ),
        (
            "schemas/trust-record.schema.json",
            serde_json::to_value(schema_for!(ExtensionTrustRecord))?,
        ),
    ])
}

fn typescript(schemas: &[(&str, Value)]) -> Result<String, serde_json::Error> {
    let mut hasher = Sha256::new();
    for (path, schema) in schemas {
        hasher.update(path.as_bytes());
        hasher.update(serde_json::to_vec(schema)?);
    }
    let fingerprint = hex::encode(hasher.finalize());
    Ok(format!(
        "// @generated by `cargo run -p theway-contract --example generate_extension_artifacts -- <output-dir>`\n// ABI schema sha256: {fingerprint}\n{TYPESCRIPT_DECLARATIONS}"
    ))
}

const TYPESCRIPT_DECLARATIONS: &str = r#"
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type ExtensionAbiMajor = 2;
export type ExtensionScope = "process" | "session" | "run" | "request";
export type ExtensionSourceLayer = "global" | "project";
export type ExtensionPermission =
  | "session.write"
  | "tools.register"
  | "tools.override"
  | "commands.register"
  | "providers.register"
  | "client.contribute"
  | "workspace.read"
  | "workspace.write"
  | "process.spawn"
  | "network.connect"
  | "provider.raw"
  | `secrets.read:${string}`;

export interface ExtensionPackageManifest {
  id: string;
  version: string;
  abi: ExtensionAbiMajor;
  entry: string;
  priority?: number;
  scope: ExtensionScope;
  stateSchema?: number;
  permissions?: ExtensionPermission[];
  optionalPermissions?: ExtensionPermission[];
}

export type ExtensionTrustSubject =
  | { kind: "project"; canonicalRoot: string }
  | { kind: "package"; extensionId: string; canonicalPath: string; contentSha256: string };
export type ExtensionTrustDecision = "trusted" | "denied";
export interface ExtensionTrustRecord {
  subject: ExtensionTrustSubject;
  permissions: ExtensionPermission[];
  decision: ExtensionTrustDecision;
  decidedAt: string;
}

export type ExtensionLifecycleEvent =
  | "extension_load" | "session_start" | "input"
  | "before_session_switch" | "session_switched" | "before_session_fork" | "session_forked"
  | "before_model_selection" | "model_selected" | "before_run" | "run_started"
  | "turn_started" | "context" | "before_model_request"
  | "before_provider_request_headers" | "before_provider_request_raw"
  | "provider_response" | "provider_request_failed"
  | "message_start" | "message_update" | "message_end" | "tool_call"
  | "tool_execution_start" | "tool_execution_update" | "tool_execution_end" | "tool_result"
  | "turn_completed" | "run_ended" | "run_error" | "run_settled"
  | "before_compaction" | "compaction_succeeded" | "compaction_failed"
  | "session_shutdown" | "extension_unload";
export interface ExtensionScopeIds {
  runId?: string;
  turnId?: string;
  requestId?: string;
  messageId?: string;
  toolCallId?: string;
}
export interface ExtensionModelRef { provider: string; model: string }
export interface ExtensionCancellationContext { cancelled?: boolean; deadlineUnixMs?: number }
export interface ExtensionEventContext {
  extensionId: string;
  sessionId: string;
  cwd: string;
  sequence: number;
  scope?: ExtensionScopeIds;
  model?: ExtensionModelRef;
  hasInteractiveClient?: boolean;
  cancellation?: ExtensionCancellationContext;
}
export interface ExtensionEventEnvelope {
  abiMajor: ExtensionAbiMajor;
  event: ExtensionLifecycleEvent;
  context: ExtensionEventContext;
  payload: JsonValue;
}

export type ExtensionHookClass = "observe" | "transform" | "gate" | "register";
export type ExtensionHookDeadline = "fast" | "standard" | "long";
export type ExtensionDeliveryPolicy = "inline" | "bounded_coalescing";
export type ExtensionHookFailurePolicy = "continue" | "keep_last_value" | "deny" | "reject_registration";
export type ExtensionActionKind =
  | "replace_input" | "patch_run_context" | "replace_context" | "replace_model_request"
  | "replace_provider_headers" | "replace_provider_payload" | "replace_message" | "replace_tool_result"
  | "set_state" | "delete_state" | "append_custom_event" | "append_model_context"
  | "emit_command_outcome" | "enqueue_follow_up" | "emit_diagnostic" | "register_effect" | "dispose_effect";
export interface ExtensionAction { kind: ExtensionActionKind; payload: { [key: string]: JsonValue } }
export type ExtensionGateDecision =
  | { decision: "abstain" }
  | { decision: "allow" }
  | { decision: "deny"; code: string; message: string }
  | { decision: "cancel"; code: string; message: string };
export interface ExtensionActionBatch {
  abiMajor: ExtensionAbiMajor;
  decision?: ExtensionGateDecision;
  actions?: ExtensionAction[];
}
export interface ExtensionHookContract {
  event: ExtensionLifecycleEvent;
  class: ExtensionHookClass;
  allowedActions: ExtensionActionKind[];
  deadline: ExtensionHookDeadline;
  delivery: ExtensionDeliveryPolicy;
  failure: ExtensionHookFailurePolicy;
}

export type ExtensionStateMutation = { operation: "set"; value: JsonValue } | { operation: "delete" };
export type ExtensionModelContextPlacement = "system_prompt_section" | "message";
export type ExtensionDurableEntryPayload =
  | { kind: "state_mutation"; key: string; mutation: ExtensionStateMutation }
  | { kind: "custom_event"; eventId: string; customType: string; payload: JsonValue }
  | { kind: "model_context"; contextId: string; placement: ExtensionModelContextPlacement; content: JsonValue }
  | { kind: "state_migration"; fromSchemaVersion: number; toSchemaVersion: number };
export interface ExtensionDurableEntry {
  abiMajor: ExtensionAbiMajor;
  extensionId: string;
  stateSchemaVersion: number;
  originSequence: number;
  entry: ExtensionDurableEntryPayload;
}

export type ExtensionCatalogStatus = "effective" | "shadowed" | "rejected" | "blocked" | "disabled" | "faulted";
export type ExtensionDiagnosticSeverity = "info" | "warning" | "error";
export type ExtensionDiagnosticCode =
  | "manifest_invalid" | "abi_unsupported" | "shadowed" | "trust_required" | "permission_denied"
  | "load_failed" | "hook_failed" | "hook_timed_out" | "cancelled" | "resource_limit"
  | "circuit_opened" | "unloaded" | "reload_pending" | "state_migration_failed"
  | "persistence_failed" | "queue_overflow" | "contract_violation";
export interface ExtensionCatalogEntry {
  extensionId: string;
  version: string;
  abiMajor: ExtensionAbiMajor;
  source: ExtensionSourceLayer;
  scope: ExtensionScope;
  priority: number;
  status: ExtensionCatalogStatus;
  permissions?: ExtensionPermission[];
  reasonCode?: ExtensionDiagnosticCode;
}
export interface ExtensionDiagnostic {
  extensionId: string;
  code: ExtensionDiagnosticCode;
  severity: ExtensionDiagnosticSeverity;
  message: string;
  sessionId?: string;
  event?: ExtensionLifecycleEvent;
  sequence?: number;
  details?: { [key: string]: JsonValue };
  redactedFields?: string[];
}

export interface ExtensionCommandDescriptor {
  name: string;
  label: string;
  description: string;
  argumentSchema: { [key: string]: JsonValue };
}
export type ExtensionCommandOutcome =
  | { status: "success"; message?: string; data?: JsonValue }
  | { status: "rejected"; code: string; message: string }
  | { status: "cancelled"; code: string; message: string };
export type ExtensionNoticeLevel = "info" | "success" | "warning" | "error";
export type ExtensionClientContributionData =
  | { kind: "notification"; level: ExtensionNoticeLevel; title: string; body: string }
  | { kind: "status_item"; label: string; value: string; detail?: string }
  | { kind: "command"; command: ExtensionCommandDescriptor }
  | { kind: "detail_panel"; title: string; data: JsonValue }
  | { kind: "form_action"; title: string; schema: JsonValue; submitCommand: string };
export interface ExtensionClientContribution {
  contributionId: string;
  extensionId: string;
  scope: ExtensionScope;
  contribution: ExtensionClientContributionData;
}
"#;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .ok_or("usage: generate_extension_artifacts <output-dir>")?;
    generate(&output)
}
